### PR TITLE
Aliases

### PR DESCRIPTION
**Pull request by ValentinRapp**
full support of aliases, with alias and unalias working as intended

### CODE REVIEW

**Review by LouisDupraz — CHANGES_REQUESTED** [review]
Rebase ta branche

**Comment by LouisDupraz** [comment]
+ coding style

**Review by PasVegan — CHANGES_REQUESTED** [review]
ca compile pas

**Review by LouisDupraz — CHANGES_REQUESTED** [review]
Ajoute des unit tests.
Les alias ne marchent pas
[https://cdn.discordapp.com/attachments/1094906869849542677/1105136126454415421/image.png](url)

**Comment by LouisDupraz** [comment]
STOP

**Pull request closed without merging**
